
server:
  port: 8848

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lab_system?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
